CREATE TABLE IF NOT EXISTS "verification_mail_code" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  code VARCHAR(8) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '15 minutes',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT "fk_user_verification_mail_code"
  FOREIGN KEY ("username")
  REFERENCES "user"("username")
  ON DELETE CASCADE
);

CREATE INDEX "idx_verification_mail_code" ON "verification_mail_code" ("username", "code");