-- This migration has the purpose of renaming the paternal_surname and maternal_surname columns to 
-- first_surname and second_surname, respectively, in the "user" table. 
-- Additionally, it will rename the "user_maternal_surname" table to "user_second_surname".

ALTER TABLE "user" 
RENAME COLUMN paternal_surname TO first_surname;

ALTER TABLE "user_maternal_surname"
RENAME TO "user_second_surname";

ALTER TABLE "user_second_surname"
RENAME COLUMN maternal_surname TO second_surname;