-- This migration has the purpose of update and populating the table "interface" 

UPDATE "interface" SET 
name = 'Perfil' WHERE id = 1;

UPDATE "interface" SET 
name = 'Habilidad blanda' WHERE id = 2;

UPDATE "interface" SET 
name = 'Habilidad tecnica' WHERE id = 3;


INSERT INTO "interface" VALUES
(4, 'Experiencia laboral'),(5, 'Formacion academica'),(6, 'Proyecto personal'),
(7, 'Certificado'),(8, 'Curriculum vitae'),(9,'Reportes');