-- This migration has the purpose of delete old values and populating the table "function_interface" 

DELETE FROM "function_interface";

INSERT INTO "function_interface" VALUES
(1,1),(2,1),(3,1),(35,1),(36,1),
(4,2),(5,2),(6,2),(7,2),(8,2),
(9,3),(10,3),(11,3),(12,3),(13,3),
(14,4),(15,4),(16,4),(17,4),(18,4),
(19,5),(20,5),(21,5),(22,5),(23,5),
(24,6),(25,6),(26,6),(27,6),(28,6),
(29,7),(30,7),(31,7),(32,7),(33,7),
(38,8),(39,9),(40,9);